# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dd79f7d86799c6393a2fedbef6f9c303ddd2702db4ab6a44860eaba35bcb79ca471fc50f2750db6765863c5fd2cafec0fc6770d09fc3e6460c339531758c4d1

test:
  secret_key_base: 8683491024fd8ea5fae6ea23e0184cedac6efa5128669694f86df951ab11921af7da058f19c4fd85e611bc033b9fc355f1862bb09e3537c6d62e0f741abfb612

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
